on:
  workflow_call:
    inputs:
      web-player-env:
        required: true
        type: string
      game-name:
        required: true
        type: string
      url-prefix:
        required: true
        type: string
      compression:
        required: true
        type: string
    secrets:
      web-player-repo-pat:
        required: true

jobs:
  update-web-player-registry:
    runs-on: ubuntu-latest
    name: Update Web Player Registry
    steps:
      - name: Update Web Player Registry
        uses: ryanditjia/demo-actions@registry
        with:
          web-player-repo-pat: ${{ secrets.web-player-repo-pat }}
          web-player-env: ${{ inputs.web-player-env }}
          game-name: ${{ inputs.game-name }}
          url-prefix: ${{ inputs.url-prefix }}
          compression: ${{ inputs.compression }}
